email:
    validation:
        regex: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
server:
    port: 8080
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: password
        url: jdbc:h2:mem:testdb
        username: sa
    h2:
        console:
            enabled: true
            path: /h2-console
spring-doc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui

